### ISSUE TITLE
Inconsistent error capitalization in errors.rst

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync#70]
For example, one of the section headers is capitalized `Object Not Found`, while the error text inside the section is capitalized `Object not found`. Also, two of the errors (`Method Not Found` and `Bad Query Value`) capitalize every word instead of just capitalizing the first word like the other letters.

timesync-node currently uses the capitalizations as they appear in the error text. Even if the capitalizations aren't standardized right away, at the very least the section headers should be changed to match the capitalizations of the error text in order to reduce confusion.

**Comment by mathuin** [comment]
Having the words in the section headers capitalized (all or first) is a documentation style issue.

The fact that they are different from the code block is not necessarily a problem.  The code blocks have to match the actual Javascript in the API code, that's more important than the capitalization matching the section headers.

That being said, would you prefer all words capitalized or first word only?  I will make either change, just tell me which one you want.

**Comment by mathuin** [comment]
Oooh.  Sorry about that.  I see what you mean now.

I have changed `"Method Not Allowed"` to `"Method not allowed"` as that's what's in the reference implementation.  

I have also changed `"Bad Query Value"` but because that's actually what's in the reference implementation, I also made osuosl/timesync-node#317 to change the text value, and included in that PR comment a link to this issue.
